// =============================================================================
// PROJECT SUB-TASKS - COO PERSPECTIVE
// Comprehensive execution breakdown covering all phases of project delivery
// =============================================================================

import type { SubTask, ProjectSubTasks } from './api';

// Helper to create a properly structured sub-task with all COO fields
function createTask(
  id: string,
  title: string,
  phase: SubTask['phase'],
  owner: string,
  data: Partial<SubTask>
): SubTask {
  return {
    id,
    title,
    description: data.description || '',
    phase,
    owner,
    stakeholders: data.stakeholders || [],
    estimatedHours: data.estimatedHours || '4-8h',
    difficulty: data.difficulty || 'Medium',
    toolsNeeded: data.toolsNeeded || [],
    knowledgeAreas: data.knowledgeAreas || ['Business Logic'],
    aiPotential: data.aiPotential || 'Medium',
    aiAssistDescription: data.aiAssistDescription || '',
    dependsOnTasks: data.dependsOnTasks || [],
    blockedBy: data.blockedBy || [],
    sharedWithProjects: data.sharedWithProjects || [],
    isFoundational: data.isFoundational || false,
    acceptanceCriteria: data.acceptanceCriteria || [],
    successMetrics: data.successMetrics || [],
    risks: data.risks || [],
    status: data.status || 'Not Started',
  };
}

export function getProjectSubTasksCOO(): ProjectSubTasks[] {
  return [
    // =========================================================================
    // 🏗️ UNIFIED DATA LAYER (API)
    // =========================================================================
    {
      projectId: 'unified-data-layer',
      totalEstimatedHours: '180-240h',
      criticalPath: ['udl-1', 'udl-2', 'udl-3', 'udl-6', 'udl-9', 'udl-11', 'udl-12'],
      subTasks: [
        // DISCOVERY PHASE
        createTask('udl-1', 'Data Audit & Gap Analysis', 'Discovery', 'Tech Lead', {
          description: 'Audit all existing data sources (Zoho, Woztell, Aircall, Holded). Document current data flows, identify gaps, inconsistencies, and missing fields. Create data dictionary.',
          stakeholders: ['CEO', 'Sales Lead', 'Operations', 'Finance'],
          estimatedHours: '16-24h',
          difficulty: 'Medium',
          toolsNeeded: ['Notion', 'Spreadsheets', 'Existing system access'],
          knowledgeAreas: ['Data Analytics', 'Business Logic'],
          aiPotential: 'Medium',
          aiAssistDescription: 'Can help analyze data schemas and generate documentation templates',
          acceptanceCriteria: [
            'Complete inventory of all data sources',
            'Data dictionary with field definitions',
            'Gap analysis document with prioritized missing data',
            'Data flow diagrams for current state',
          ],
          successMetrics: ['100% of data sources documented', 'All critical gaps identified'],
          risks: ['Access delays to production systems', 'Undocumented legacy data'],
        }),
        createTask('udl-2', 'Stakeholder Requirements Workshop', 'Discovery', 'COO', {
          description: 'Conduct workshops with Sales, Ops, Finance, and Leadership to understand data needs. Document use cases, reporting requirements, and pain points.',
          stakeholders: ['CEO', 'Sales Team', 'Operations', 'Finance', 'Installers'],
          estimatedHours: '8-12h',
          difficulty: 'Easy',
          toolsNeeded: ['Meeting tools', 'Notion', 'Whiteboard'],
          knowledgeAreas: ['Stakeholder Management', 'Business Logic'],
          aiPotential: 'Low',
          aiAssistDescription: 'Can help structure workshop agenda and document outputs',
          dependsOnTasks: ['udl-1'],
          acceptanceCriteria: [
            'Workshop conducted with all key stakeholders',
            'Requirements document approved by stakeholders',
            'Priority ranking of data needs',
            'Success criteria defined for each use case',
          ],
          risks: ['Stakeholder availability', 'Conflicting requirements'],
        }),

        // PLANNING PHASE
        createTask('udl-3', 'API Architecture Design', 'Planning', 'Tech Lead', {
          description: 'Design API architecture including endpoints, authentication, rate limiting, caching strategy. Define data models and relationships. Create technical specification document.',
          stakeholders: ['Tech Team', 'Security'],
          estimatedHours: '20-30h',
          difficulty: 'Hard',
          toolsNeeded: ['Architecture tools', 'Documentation'],
          knowledgeAreas: ['API Integration', 'Database/SQL', 'Security/Auth'],
          aiPotential: 'High',
          aiAssistDescription: 'Can generate OpenAPI specs, data models, and architecture diagrams',
          dependsOnTasks: ['udl-1', 'udl-2'],
          acceptanceCriteria: [
            'OpenAPI specification document',
            'Database schema design',
            'Authentication flow documented',
            'Caching strategy defined',
            'Rate limiting rules specified',
          ],
          isFoundational: true,
          sharedWithProjects: ['reporting-hub', 'sdr-portal', 'installer-portal-product'],
        }),
        createTask('udl-4', 'Third-Party API Access & Contracts', 'Planning', 'Operations', {
          description: 'Secure API access and documentation for all third-party systems. Negotiate contracts if needed. Document API limits, costs, and SLAs.',
          stakeholders: ['Finance', 'Legal', 'Vendors'],
          estimatedHours: '8-16h',
          difficulty: 'Medium',
          toolsNeeded: ['Contract management', 'Vendor portals'],
          knowledgeAreas: ['Vendor Management', 'Compliance/Legal'],
          aiPotential: 'Low',
          aiAssistDescription: 'Vendor negotiation requires human judgment',
          blockedBy: ['Vendor response times', 'Contract approval'],
          acceptanceCriteria: [
            'Zoho API access confirmed with documented limits',
            'Woztell API access and documentation obtained',
            'Aircall API credentials and documentation',
            'Holded API access for financial data',
            'All API rate limits and costs documented',
          ],
          risks: ['Vendor delays', 'Unexpected costs', 'API limitations'],
        }),

        // DEVELOPMENT PHASE
        createTask('udl-5', 'Core API Infrastructure Setup', 'Development', 'Developer', {
          description: 'Set up API server, database, authentication system, logging, and monitoring. Deploy to staging environment.',
          stakeholders: ['Tech Team'],
          estimatedHours: '24-32h',
          difficulty: 'Hard',
          toolsNeeded: ['Node.js', 'PostgreSQL', 'Vercel/Railway', 'Auth0/JWT'],
          knowledgeAreas: ['API Integration', 'Database/SQL', 'DevOps', 'Security/Auth'],
          aiPotential: 'High',
          aiAssistDescription: 'Can generate boilerplate code, database migrations, and deployment configs',
          dependsOnTasks: ['udl-3', 'udl-4'],
          acceptanceCriteria: [
            'API server running in staging',
            'Database deployed and accessible',
            'Authentication system working',
            'Logging and monitoring active',
            'CI/CD pipeline configured',
          ],
          isFoundational: true,
        }),
        createTask('udl-6', 'Deals & Opportunities Endpoints', 'Development', 'Developer', {
          description: 'Build endpoints for Deals and Opportunities including CRUD operations, filtering, pagination, and Zoho sync.',
          stakeholders: ['Sales Team', 'Operations'],
          estimatedHours: '20-28h',
          difficulty: 'Medium',
          toolsNeeded: ['Node.js', 'PostgreSQL', 'Zoho API'],
          knowledgeAreas: ['API Integration', 'Database/SQL'],
          aiPotential: 'High',
          aiAssistDescription: 'Can generate CRUD endpoints, data models, and sync logic',
          dependsOnTasks: ['udl-5'],
          acceptanceCriteria: [
            'GET /deals with pagination and filters',
            'GET /deals/:id with full details',
            'GET /deals/stats with aggregations',
            'GET /opportunities with installer filter',
            'Real-time sync with Zoho CRM',
            'Stage change timestamps captured',
          ],
          sharedWithProjects: ['reporting-hub', 'sdr-portal'],
        }),
        createTask('udl-7', 'Calls & Qualifications Endpoints', 'Development', 'Developer', {
          description: 'Build endpoints for Calls and Qualifications data. Integrate with Aircall for call data. Support transcription storage.',
          stakeholders: ['SDR Team', 'Operations'],
          estimatedHours: '16-24h',
          difficulty: 'Medium',
          toolsNeeded: ['Node.js', 'PostgreSQL', 'Aircall API'],
          knowledgeAreas: ['API Integration', 'Database/SQL', 'External APIs'],
          aiPotential: 'Medium',
          aiAssistDescription: 'Can generate API integration code and data models',
          dependsOnTasks: ['udl-5'],
          acceptanceCriteria: [
            'GET /calls with pagination and date filters',
            'GET /calls/:id with recording URL',
            'Call transcripts stored and searchable',
            'GET /qualifications with deal linkage',
            'Aircall webhook integration working',
          ],
          sharedWithProjects: ['ai-cortex', 'contact-prioritization-engine'],
        }),
        createTask('udl-8', 'WhatsApp Conversation History', 'Development', 'Developer', {
          description: 'Build endpoints for WhatsApp conversation history. Integrate with Woztell API to pull full message history per deal.',
          stakeholders: ['SDR Team', 'Operations'],
          estimatedHours: '20-30h',
          difficulty: 'Hard',
          toolsNeeded: ['Node.js', 'PostgreSQL', 'Woztell API'],
          knowledgeAreas: ['API Integration', 'Database/SQL', 'External APIs'],
          aiPotential: 'Medium',
          aiAssistDescription: 'Can help with data mapping and pagination handling',
          dependsOnTasks: ['udl-5', 'udl-4'],
          blockedBy: ['Woztell API documentation'],
          acceptanceCriteria: [
            'GET /deals/:id/messages with full history',
            'Message direction (inbound/outbound) tracked',
            'Timestamps accurate to the second',
            'Media attachments referenced',
            'Webhook for real-time updates',
          ],
          isFoundational: true,
          sharedWithProjects: ['whatsapp-conversation-summary', 'ai-cortex', 'funnel-automation-os', 'sdr-portal'],
        }),
        createTask('udl-9', 'Installers & Regions Endpoints', 'Development', 'Developer', {
          description: 'Build endpoints for Installers and Regions data. Include performance metrics, capacity, and geographic coverage.',
          stakeholders: ['Partner Ops', 'Operations'],
          estimatedHours: '12-18h',
          difficulty: 'Medium',
          toolsNeeded: ['Node.js', 'PostgreSQL'],
          knowledgeAreas: ['API Integration', 'Database/SQL'],
          aiPotential: 'High',
          aiAssistDescription: 'Can generate CRUD endpoints and relationship models',
          dependsOnTasks: ['udl-5'],
          acceptanceCriteria: [
            'GET /installers with active/inactive filter',
            'GET /installers/:id with regions and metrics',
            'GET /regions with postal code coverage',
            'Installer capacity and quota tracking',
            'Performance metrics per installer',
          ],
          sharedWithProjects: ['installer-portal-product', 'dynamic-allocation-engine'],
        }),

        // TESTING PHASE
        createTask('udl-10', 'API Testing & Quality Assurance', 'Testing', 'QA/Developer', {
          description: 'Comprehensive testing of all API endpoints. Load testing, security audit, edge case handling. Fix bugs and optimize performance.',
          stakeholders: ['Tech Team', 'Security'],
          estimatedHours: '16-24h',
          difficulty: 'Medium',
          toolsNeeded: ['Jest', 'Postman', 'Load testing tools'],
          knowledgeAreas: ['API Integration', 'Security/Auth', 'DevOps'],
          aiPotential: 'High',
          aiAssistDescription: 'Can generate test cases, mocks, and load test scripts',
          dependsOnTasks: ['udl-6', 'udl-7', 'udl-8', 'udl-9'],
          acceptanceCriteria: [
            'Unit tests for all endpoints (>80% coverage)',
            'Integration tests passing',
            'Load test: handles 100 req/s',
            'Security audit completed',
            'No critical/high bugs',
            'Response times <500ms for 95% of requests',
          ],
        }),

        // TRAINING & DOCUMENTATION PHASE
        createTask('udl-11', 'API Documentation & Developer Guide', 'Training', 'Tech Lead', {
          description: 'Create comprehensive API documentation with examples. Build interactive API explorer. Write developer onboarding guide.',
          stakeholders: ['Tech Team', 'External Developers'],
          estimatedHours: '12-16h',
          difficulty: 'Easy',
          toolsNeeded: ['Swagger/OpenAPI', 'Documentation platform'],
          knowledgeAreas: ['Training & Documentation', 'API Integration'],
          aiPotential: 'High',
          aiAssistDescription: 'Can generate documentation from OpenAPI spec and code comments',
          dependsOnTasks: ['udl-10'],
          acceptanceCriteria: [
            'Interactive API documentation live',
            'All endpoints documented with examples',
            'Authentication guide complete',
            'Error code reference',
            'Developer quickstart guide',
            'Postman collection published',
          ],
        }),

        // ROLLOUT PHASE
        createTask('udl-12', 'Production Deployment & Monitoring', 'Rollout', 'Tech Lead', {
          description: 'Deploy API to production. Set up monitoring, alerting, and dashboards. Configure backup and disaster recovery.',
          stakeholders: ['Tech Team', 'Operations'],
          estimatedHours: '8-12h',
          difficulty: 'Medium',
          toolsNeeded: ['Vercel/Railway', 'Monitoring tools', 'Alerting'],
          knowledgeAreas: ['DevOps', 'Security/Auth'],
          aiPotential: 'Medium',
          aiAssistDescription: 'Can help with deployment configs and monitoring setup',
          dependsOnTasks: ['udl-10', 'udl-11'],
          acceptanceCriteria: [
            'API live in production',
            'Health check endpoint responding',
            'Monitoring dashboard configured',
            'Alerts set for errors and latency',
            'Database backups scheduled',
            'Runbook for incident response',
          ],
          successMetrics: ['99.9% uptime', '<200ms avg response time', 'Zero data loss'],
        }),

        // MONITORING PHASE
        createTask('udl-13', 'Ongoing Maintenance & Iteration', 'Monitoring', 'Tech Lead', {
          description: 'Establish ongoing maintenance process. Weekly review of API health, performance optimization, bug fixes, and feature requests.',
          stakeholders: ['All Teams'],
          estimatedHours: 'Ongoing (4h/week)',
          difficulty: 'Easy',
          toolsNeeded: ['Monitoring tools', 'Issue tracker'],
          knowledgeAreas: ['DevOps', 'Stakeholder Management'],
          aiPotential: 'Medium',
          aiAssistDescription: 'Can help analyze logs, identify patterns, and suggest optimizations',
          dependsOnTasks: ['udl-12'],
          acceptanceCriteria: [
            'Weekly health review process established',
            'SLA monitoring in place',
            'Feature request backlog maintained',
            'Incident response process documented',
          ],
          successMetrics: ['API health score >95%', 'All critical bugs fixed within 24h'],
        }),
      ],
    },

    // =========================================================================
    // 📊 REPORTING HUB
    // =========================================================================
    {
      projectId: 'reporting-hub',
      totalEstimatedHours: '120-160h',
      criticalPath: ['rh-1', 'rh-2', 'rh-4', 'rh-6', 'rh-8', 'rh-10'],
      subTasks: [
        // DISCOVERY PHASE
        createTask('rh-1', 'KPI Discovery & Stakeholder Alignment', 'Discovery', 'COO', {
          description: 'Meet with all department heads to understand reporting needs. Define KPIs, formulas, and success thresholds. Get sign-off on metrics definitions.',
          stakeholders: ['CEO', 'Sales Lead', 'Operations', 'Finance', 'Marketing'],
          estimatedHours: '12-16h',
          difficulty: 'Medium',
          toolsNeeded: ['Meeting tools', 'Notion', 'Spreadsheets'],
          knowledgeAreas: ['Stakeholder Management', 'Data Analytics', 'Business Logic'],
          aiPotential: 'Medium',
          aiAssistDescription: 'Can suggest industry-standard KPIs and help document formulas',
          acceptanceCriteria: [
            'KPI catalog with definitions approved by stakeholders',
            'Formulas documented and validated',
            'Thresholds defined (good/warning/critical)',
            'Data sources identified for each KPI',
            'Reporting frequency agreed (real-time, daily, weekly)',
          ],
          risks: ['Conflicting priorities between departments', 'Undefined metrics'],
        }),
        createTask('rh-2', 'Current State Analysis', 'Discovery', 'Operations', {
          description: 'Audit existing reports and dashboards. Identify manual reporting processes that can be automated. Document pain points and gaps.',
          stakeholders: ['All Teams'],
          estimatedHours: '8-12h',
          difficulty: 'Easy',
          toolsNeeded: ['Existing tools', 'Documentation'],
          knowledgeAreas: ['Data Analytics', 'Process Design'],
          aiPotential: 'Medium',
          aiAssistDescription: 'Can help analyze and categorize existing reports',
          dependsOnTasks: ['rh-1'],
          acceptanceCriteria: [
            'Inventory of all existing reports',
            'Time spent on manual reporting quantified',
            'Pain points documented',
            'Automation opportunities identified',
          ],
        }),

        // PLANNING PHASE
        createTask('rh-3', 'Dashboard Design & Wireframes', 'Planning', 'UX/Product', {
          description: 'Design dashboard layouts, information hierarchy, and user flows. Create wireframes for each stakeholder view. Get design approval.',
          stakeholders: ['CEO', 'Department Heads', 'End Users'],
          estimatedHours: '12-16h',
          difficulty: 'Medium',
          toolsNeeded: ['Figma', 'Wireframing tools'],
          knowledgeAreas: ['UX Design', 'Data Analytics'],
          aiPotential: 'Medium',
          aiAssistDescription: 'Can suggest dashboard layouts and best practices',
          dependsOnTasks: ['rh-1'],
          acceptanceCriteria: [
            'Wireframes for executive dashboard',
            'Wireframes for department-specific views',
            'Mobile-responsive design considered',
            'Design approved by key stakeholders',
          ],
        }),
        createTask('rh-4', 'Data Pipeline Architecture', 'Planning', 'Tech Lead', {
          description: 'Design data pipeline for KPI calculations. Define aggregation schedules, caching strategy, and historical data retention.',
          stakeholders: ['Tech Team'],
          estimatedHours: '8-12h',
          difficulty: 'Hard',
          toolsNeeded: ['Architecture tools', 'Documentation'],
          knowledgeAreas: ['Database/SQL', 'Data Analytics', 'DevOps'],
          aiPotential: 'High',
          aiAssistDescription: 'Can help design data models and aggregation logic',
          dependsOnTasks: ['rh-1', 'rh-2'],
          acceptanceCriteria: [
            'Data pipeline architecture documented',
            'Aggregation schedules defined',
            'Caching strategy for real-time KPIs',
            'Historical data retention policy',
            'API endpoints defined for dashboard',
          ],
          isFoundational: true,
          sharedWithProjects: ['investor-portal', 'campaign-os'],
        }),

        // DEVELOPMENT PHASE
        createTask('rh-5', 'KPI Calculation Engine', 'Development', 'Developer', {
          description: 'Build backend service for computing KPIs. Implement aggregations, calculations, and caching. Create API endpoints for dashboard.',
          stakeholders: ['Tech Team'],
          estimatedHours: '24-32h',
          difficulty: 'Hard',
          toolsNeeded: ['Node.js', 'PostgreSQL', 'Redis'],
          knowledgeAreas: ['Database/SQL', 'Data Analytics', 'API Integration'],
          aiPotential: 'High',
          aiAssistDescription: 'Can generate SQL queries, aggregation logic, and API handlers',
          dependsOnTasks: ['rh-4'],
          acceptanceCriteria: [
            'All KPIs calculating correctly',
            'Real-time KPIs updating within 5 seconds',
            'Historical snapshots stored daily',
            'API endpoints returning correct data',
            'Performance: calculations complete in <2s',
          ],
          sharedWithProjects: ['investor-portal'],
        }),
        createTask('rh-6', 'Dashboard Frontend Development', 'Development', 'Developer', {
          description: 'Build React dashboard with charts, tables, and filters. Implement responsive design and real-time updates.',
          stakeholders: ['All Teams'],
          estimatedHours: '32-40h',
          difficulty: 'Medium',
          toolsNeeded: ['React', 'Recharts/Chart.js', 'Tailwind'],
          knowledgeAreas: ['Frontend/React', 'UX Design', 'Data Analytics'],
          aiPotential: 'High',
          aiAssistDescription: 'Can generate chart components, layouts, and styling',
          dependsOnTasks: ['rh-3', 'rh-5'],
          acceptanceCriteria: [
            'Executive dashboard complete',
            'Department views implemented',
            'Charts rendering correctly',
            'Filters and date ranges working',
            'Mobile responsive',
            'Real-time updates functioning',
          ],
          isFoundational: true,
          sharedWithProjects: ['investor-portal', 'installer-portal-product', 'sdr-portal'],
        }),
        createTask('rh-7', 'Export & Scheduling Features', 'Development', 'Developer', {
          description: 'Add PDF/Excel export functionality. Implement scheduled email reports with customizable frequency.',
          stakeholders: ['Leadership', 'Operations'],
          estimatedHours: '12-16h',
          difficulty: 'Medium',
          toolsNeeded: ['React-PDF', 'Node-cron', 'SendGrid'],
          knowledgeAreas: ['Frontend/React', 'DevOps', 'API Integration'],
          aiPotential: 'High',
          aiAssistDescription: 'Can generate PDF templates and scheduling logic',
          dependsOnTasks: ['rh-6'],
          acceptanceCriteria: [
            'PDF export working for all dashboards',
            'Excel export with proper formatting',
            'Scheduled reports configurable',
            'Email delivery reliable',
          ],
        }),

        // TESTING PHASE
        createTask('rh-8', 'Data Validation & UAT', 'Testing', 'Operations/QA', {
          description: 'Validate KPI calculations against manual calculations. Conduct user acceptance testing with stakeholders. Fix discrepancies.',
          stakeholders: ['Finance', 'Sales Lead', 'Operations'],
          estimatedHours: '16-24h',
          difficulty: 'Medium',
          toolsNeeded: ['Spreadsheets', 'Testing tools'],
          knowledgeAreas: ['Data Analytics', 'Business Logic'],
          aiPotential: 'Medium',
          aiAssistDescription: 'Can help generate test cases and validation scripts',
          dependsOnTasks: ['rh-6', 'rh-7'],
          acceptanceCriteria: [
            'All KPIs validated against source data',
            'Finance sign-off on financial metrics',
            'Sales sign-off on pipeline metrics',
            'No calculation discrepancies',
            'UAT sign-off from all stakeholders',
          ],
          risks: ['Discrepancies between systems', 'Stakeholder availability for UAT'],
        }),

        // TRAINING PHASE
        createTask('rh-9', 'Training & Documentation', 'Training', 'Operations', {
          description: 'Create user guides and video tutorials. Conduct training sessions for each department. Document KPI definitions and interpretations.',
          stakeholders: ['All Teams'],
          estimatedHours: '12-16h',
          difficulty: 'Easy',
          toolsNeeded: ['Documentation', 'Video recording', 'Training tools'],
          knowledgeAreas: ['Training & Documentation', 'Change Management'],
          aiPotential: 'High',
          aiAssistDescription: 'Can generate documentation and training materials',
          dependsOnTasks: ['rh-8'],
          acceptanceCriteria: [
            'User guide published',
            'Video tutorials recorded',
            'Training sessions completed',
            'KPI glossary published',
            'FAQ documented',
          ],
        }),

        // ROLLOUT PHASE
        createTask('rh-10', 'Production Launch & Adoption', 'Rollout', 'COO', {
          description: 'Deploy to production. Announce to company. Monitor adoption and gather feedback. Iterate based on user input.',
          stakeholders: ['All Teams'],
          estimatedHours: '8-12h',
          difficulty: 'Easy',
          toolsNeeded: ['Communication tools', 'Analytics'],
          knowledgeAreas: ['Change Management', 'Stakeholder Management'],
          aiPotential: 'Low',
          aiAssistDescription: 'Human change management required',
          dependsOnTasks: ['rh-8', 'rh-9'],
          acceptanceCriteria: [
            'Dashboard live in production',
            'Company announcement sent',
            'Adoption tracking in place',
            'Feedback channel established',
            'First week issues resolved',
          ],
          successMetrics: ['80% of target users accessing weekly', 'Manual reporting time reduced by 60%'],
        }),
      ],
    },

    // =========================================================================
    // 📱 SDR PORTAL
    // =========================================================================
    {
      projectId: 'sdr-portal',
      totalEstimatedHours: '160-200h',
      criticalPath: ['sdr-1', 'sdr-3', 'sdr-5', 'sdr-8', 'sdr-10', 'sdr-12', 'sdr-14'],
      subTasks: [
        // DISCOVERY PHASE
        createTask('sdr-1', 'SDR Workflow Analysis & Pain Points', 'Discovery', 'Operations', {
          description: 'Shadow SDR team for a full week. Document current workflow, tools used, time spent on each activity. Identify pain points and inefficiencies.',
          stakeholders: ['SDR Team', 'Sales Lead'],
          estimatedHours: '16-20h',
          difficulty: 'Easy',
          toolsNeeded: ['Observation', 'Documentation'],
          knowledgeAreas: ['Process Design', 'Stakeholder Management'],
          aiPotential: 'Low',
          aiAssistDescription: 'Human observation required for authentic workflow understanding',
          acceptanceCriteria: [
            'Complete SDR workflow documented',
            'Time breakdown by activity',
            'Pain points ranked by impact',
            'Tool usage mapped',
            'Improvement opportunities identified',
          ],
          risks: ['SDR availability', 'Biased self-reporting'],
        }),
        createTask('sdr-2', 'Competitive Tool Analysis', 'Discovery', 'Product', {
          description: 'Research competitor SDR tools (Salesloft, Outreach, etc.). Identify best practices and features to incorporate.',
          stakeholders: ['Sales Lead', 'Tech Lead'],
          estimatedHours: '8-12h',
          difficulty: 'Easy',
          toolsNeeded: ['Research', 'Demo accounts'],
          knowledgeAreas: ['UX Design', 'Business Logic'],
          aiPotential: 'High',
          aiAssistDescription: 'Can help research and summarize competitor features',
          acceptanceCriteria: [
            'Competitor feature matrix created',
            'Best practices documented',
            'Features prioritized for Abeto context',
          ],
        }),
        createTask('sdr-3', 'AI Use Cases Definition', 'Discovery', 'Product/COO', {
          description: 'Define specific AI use cases: conversation summaries, prioritization, scripts, objection handling. Get SDR team input on most valuable.',
          stakeholders: ['SDR Team', 'Tech Lead', 'Sales Lead'],
          estimatedHours: '8-12h',
          difficulty: 'Medium',
          toolsNeeded: ['Workshops', 'Documentation'],
          knowledgeAreas: ['LLM/Prompt Engineering', 'Business Logic'],
          aiPotential: 'Medium',
          aiAssistDescription: 'Can suggest AI use cases and help design prompts',
          dependsOnTasks: ['sdr-1'],
          acceptanceCriteria: [
            'AI use cases documented with expected impact',
            'SDR team buy-in achieved',
            'Priority ranking agreed',
            'Success metrics defined per use case',
          ],
        }),

        // PLANNING PHASE
        createTask('sdr-4', 'Portal UX Design & Prototyping', 'Planning', 'UX/Product', {
          description: 'Design portal layout, information architecture, and key screens. Create clickable prototype. User test with SDRs.',
          stakeholders: ['SDR Team', 'Sales Lead'],
          estimatedHours: '16-24h',
          difficulty: 'Medium',
          toolsNeeded: ['Figma', 'Prototyping tools'],
          knowledgeAreas: ['UX Design', 'Frontend/React'],
          aiPotential: 'Medium',
          aiAssistDescription: 'Can suggest layouts and help with design patterns',
          dependsOnTasks: ['sdr-1', 'sdr-3'],
          acceptanceCriteria: [
            'Wireframes for all key screens',
            'Clickable prototype created',
            'User testing completed with 3+ SDRs',
            'Feedback incorporated',
            'Final design approved',
          ],
        }),
        createTask('sdr-5', 'Technical Architecture', 'Planning', 'Tech Lead', {
          description: 'Design technical architecture including frontend, API integrations, real-time features, and AI components.',
          stakeholders: ['Tech Team'],
          estimatedHours: '12-16h',
          difficulty: 'Hard',
          toolsNeeded: ['Architecture tools', 'Documentation'],
          knowledgeAreas: ['API Integration', 'Frontend/React', 'LLM/Prompt Engineering'],
          aiPotential: 'High',
          aiAssistDescription: 'Can help design architecture and generate specs',
          dependsOnTasks: ['sdr-3', 'sdr-4'],
          acceptanceCriteria: [
            'Architecture diagram complete',
            'API endpoints defined',
            'Real-time strategy documented',
            'AI integration approach defined',
            'Performance requirements specified',
          ],
          isFoundational: true,
        }),

        // DEVELOPMENT PHASE
        createTask('sdr-6', 'Core Portal Framework', 'Development', 'Developer', {
          description: 'Build core portal: authentication, navigation, responsive layout. Set up API connections to unified data layer.',
          stakeholders: ['Tech Team'],
          estimatedHours: '20-28h',
          difficulty: 'Medium',
          toolsNeeded: ['React', 'Next.js', 'Tailwind'],
          knowledgeAreas: ['Frontend/React', 'Security/Auth'],
          aiPotential: 'High',
          aiAssistDescription: 'Can generate component structure, layouts, and auth flow',
          dependsOnTasks: ['sdr-5'],
          acceptanceCriteria: [
            'Authentication working',
            'Responsive layout complete',
            'Navigation implemented',
            'API connections established',
            'Core pages rendering',
          ],
        }),
        createTask('sdr-7', 'Contact List & Queue Management', 'Development', 'Developer', {
          description: 'Build contact list with filtering, sorting, and queue management. Implement click-to-call and status updates.',
          stakeholders: ['SDR Team'],
          estimatedHours: '16-24h',
          difficulty: 'Medium',
          toolsNeeded: ['React', 'Backend APIs'],
          knowledgeAreas: ['Frontend/React', 'API Integration'],
          aiPotential: 'High',
          aiAssistDescription: 'Can generate list components and filter logic',
          dependsOnTasks: ['sdr-6'],
          acceptanceCriteria: [
            'Contact list with pagination',
            'Filters working (status, date, etc.)',
            'Sorting options available',
            'Click-to-call integration',
            'Status updates in real-time',
          ],
        }),
        createTask('sdr-8', 'WhatsApp Conversation Summary (AI)', 'Development', 'Developer', {
          description: 'Integrate LLM to generate conversation summaries before calls. Show key points, sentiment, last topics discussed.',
          stakeholders: ['SDR Team', 'Tech Lead'],
          estimatedHours: '24-32h',
          difficulty: 'Hard',
          toolsNeeded: ['Claude/OpenAI API', 'React'],
          knowledgeAreas: ['LLM/Prompt Engineering', 'Frontend/React'],
          aiPotential: 'High',
          aiAssistDescription: 'Core AI feature - can generate prompts and UI components',
          dependsOnTasks: ['sdr-6'],
          blockedBy: ['WhatsApp History API (unified-data-layer)'],
          acceptanceCriteria: [
            'Summary generating for each contact',
            'Key points extracted accurately',
            'Sentiment indicator shown',
            'Last topics highlighted',
            'Summary loads in <3 seconds',
          ],
          isFoundational: true,
          sharedWithProjects: ['whatsapp-conversation-summary', 'ai-cortex'],
        }),
        createTask('sdr-9', 'AI Prioritization Engine', 'Development', 'Developer', {
          description: 'Build contact prioritization using AI scoring. Consider engagement, timing, lead quality, and conversion probability.',
          stakeholders: ['SDR Team', 'Sales Lead'],
          estimatedHours: '20-28h',
          difficulty: 'Hard',
          toolsNeeded: ['Node.js', 'LLM APIs', 'PostgreSQL'],
          knowledgeAreas: ['LLM/Prompt Engineering', 'Data Analytics', 'Business Logic'],
          aiPotential: 'High',
          aiAssistDescription: 'Can help design scoring algorithm and prompts',
          dependsOnTasks: ['sdr-7', 'sdr-8'],
          acceptanceCriteria: [
            'Scoring algorithm implemented',
            'Factors explained to user',
            'Queue auto-sorted by priority',
            'Manual override available',
            'Score accuracy >70% (validated against outcomes)',
          ],
          sharedWithProjects: ['contact-prioritization-engine'],
        }),
        createTask('sdr-10', 'Real-time AI Copilot', 'Development', 'Developer', {
          description: 'Build AI copilot panel that provides real-time suggestions, objection handling tips, and next best actions during calls.',
          stakeholders: ['SDR Team'],
          estimatedHours: '24-32h',
          difficulty: 'Hard',
          toolsNeeded: ['WebSockets', 'LLM APIs', 'React'],
          knowledgeAreas: ['LLM/Prompt Engineering', 'Frontend/React', 'DevOps'],
          aiPotential: 'High',
          aiAssistDescription: 'Core AI feature - can generate prompts and interaction patterns',
          dependsOnTasks: ['sdr-8', 'sdr-9'],
          acceptanceCriteria: [
            'Copilot panel implemented',
            'Suggestions contextually relevant',
            'Objection handling tips accurate',
            'Response time <2 seconds',
            'Can be minimized/expanded',
          ],
          isFoundational: true,
          sharedWithProjects: ['ai-cortex'],
        }),
        createTask('sdr-11', 'Performance Dashboard', 'Development', 'Developer', {
          description: 'Build SDR performance dashboard: calls made, conversions, response times, comparison to goals.',
          stakeholders: ['SDR Team', 'Sales Lead'],
          estimatedHours: '12-16h',
          difficulty: 'Medium',
          toolsNeeded: ['React', 'Charts'],
          knowledgeAreas: ['Frontend/React', 'Data Analytics'],
          aiPotential: 'High',
          aiAssistDescription: 'Can generate dashboard components and visualizations',
          dependsOnTasks: ['sdr-6'],
          acceptanceCriteria: [
            'Daily/weekly/monthly views',
            'Key metrics displayed',
            'Goal progress shown',
            'Team comparison (optional)',
            'Export functionality',
          ],
          sharedWithProjects: ['reporting-hub'],
        }),

        // TESTING PHASE
        createTask('sdr-12', 'SDR Beta Testing', 'Testing', 'Operations/QA', {
          description: 'Run beta with 2-3 SDRs for 2 weeks. Collect feedback daily. Fix critical issues. Validate AI accuracy.',
          stakeholders: ['SDR Team', 'Tech Team'],
          estimatedHours: '20-30h',
          difficulty: 'Medium',
          toolsNeeded: ['Feedback tools', 'Analytics'],
          knowledgeAreas: ['Process Design', 'Data Analytics'],
          aiPotential: 'Low',
          aiAssistDescription: 'Human testing and feedback collection required',
          dependsOnTasks: ['sdr-10', 'sdr-11'],
          acceptanceCriteria: [
            'Beta running for 2 weeks',
            'Daily feedback collected',
            'Critical bugs fixed',
            'AI accuracy validated (>70%)',
            'SDR satisfaction >7/10',
          ],
          risks: ['SDR resistance to change', 'AI hallucinations'],
        }),

        // TRAINING PHASE
        createTask('sdr-13', 'SDR Training Program', 'Training', 'Operations', {
          description: 'Create training materials. Conduct hands-on training sessions. Document best practices for using AI features.',
          stakeholders: ['SDR Team', 'Sales Lead'],
          estimatedHours: '12-16h',
          difficulty: 'Easy',
          toolsNeeded: ['Training materials', 'Video recording'],
          knowledgeAreas: ['Training & Documentation', 'Change Management'],
          aiPotential: 'High',
          aiAssistDescription: 'Can generate training materials and documentation',
          dependsOnTasks: ['sdr-12'],
          acceptanceCriteria: [
            'Training materials created',
            'All SDRs trained',
            'Best practices documented',
            'Quick reference guide published',
            'Training satisfaction >8/10',
          ],
        }),

        // ROLLOUT PHASE
        createTask('sdr-14', 'Full Team Rollout', 'Rollout', 'Operations', {
          description: 'Roll out to full SDR team. Monitor adoption and performance. Provide support. Iterate based on feedback.',
          stakeholders: ['SDR Team', 'Sales Lead', 'COO'],
          estimatedHours: '12-20h',
          difficulty: 'Medium',
          toolsNeeded: ['Support tools', 'Analytics'],
          knowledgeAreas: ['Change Management', 'Stakeholder Management'],
          aiPotential: 'Low',
          aiAssistDescription: 'Human change management required',
          dependsOnTasks: ['sdr-13'],
          acceptanceCriteria: [
            'All SDRs using portal daily',
            'Old tools deprecated',
            'Support process established',
            'Weekly feedback reviews',
            'Performance baseline established',
          ],
          successMetrics: [
            '100% SDR adoption within 2 weeks',
            '20% reduction in time per lead',
            '15% improvement in contact rate',
            'SDR satisfaction >8/10',
          ],
        }),

        // MONITORING PHASE
        createTask('sdr-15', 'Continuous Improvement', 'Monitoring', 'Product', {
          description: 'Establish continuous improvement process. Track KPIs, collect feedback, prioritize enhancements.',
          stakeholders: ['SDR Team', 'Sales Lead'],
          estimatedHours: 'Ongoing (4h/week)',
          difficulty: 'Easy',
          toolsNeeded: ['Analytics', 'Feedback tools'],
          knowledgeAreas: ['Data Analytics', 'Stakeholder Management'],
          aiPotential: 'Medium',
          aiAssistDescription: 'Can analyze usage patterns and suggest improvements',
          dependsOnTasks: ['sdr-14'],
          acceptanceCriteria: [
            'KPI tracking dashboard live',
            'Monthly feedback review process',
            'Enhancement backlog maintained',
            'Quarterly improvement targets set',
          ],
        }),
      ],
    },

    // =========================================================================
    // 🔧 INSTALLER PORTAL
    // =========================================================================
    {
      projectId: 'installer-portal-product',
      totalEstimatedHours: '180-240h',
      criticalPath: ['ip-1', 'ip-3', 'ip-5', 'ip-7', 'ip-10', 'ip-12', 'ip-14'],
      subTasks: [
        // DISCOVERY PHASE
        createTask('ip-1', 'Installer Needs Assessment', 'Discovery', 'Partner Ops', {
          description: 'Interview 5+ installers to understand their workflow, pain points, and portal needs. Document current communication methods and inefficiencies.',
          stakeholders: ['Installers', 'Partner Ops', 'Operations'],
          estimatedHours: '12-16h',
          difficulty: 'Easy',
          toolsNeeded: ['Interviews', 'Documentation'],
          knowledgeAreas: ['Stakeholder Management', 'Process Design'],
          aiPotential: 'Low',
          aiAssistDescription: 'Human relationship building required',
          acceptanceCriteria: [
            '5+ installer interviews completed',
            'Pain points documented and prioritized',
            'Feature wishlist created',
            'Current workflow mapped',
            'Success criteria defined with installers',
          ],
          risks: ['Installer availability', 'Varied needs across installers'],
        }),
        createTask('ip-2', 'Legal & Compliance Review', 'Discovery', 'Legal/Operations', {
          description: 'Review legal requirements for installer portal: data access, GDPR, terms of service, liability. Engage legal counsel if needed.',
          stakeholders: ['Legal', 'Finance', 'Installers'],
          estimatedHours: '8-12h',
          difficulty: 'Medium',
          toolsNeeded: ['Legal review', 'Documentation'],
          knowledgeAreas: ['Compliance/Legal'],
          aiPotential: 'Low',
          aiAssistDescription: 'Legal expertise required',
          acceptanceCriteria: [
            'Data access policy defined',
            'Terms of service drafted',
            'GDPR compliance verified',
            'Liability boundaries clear',
            'Legal sign-off obtained',
          ],
          risks: ['Legal delays', 'Compliance gaps'],
        }),

        // PLANNING PHASE
        createTask('ip-3', 'Portal Feature Specification', 'Planning', 'Product', {
          description: 'Define portal features in detail: lead management, performance metrics, feedback, quotes, notifications. Prioritize MVP vs. future.',
          stakeholders: ['Installers', 'Partner Ops', 'Tech Lead'],
          estimatedHours: '12-16h',
          difficulty: 'Medium',
          toolsNeeded: ['Documentation', 'Prioritization frameworks'],
          knowledgeAreas: ['Business Logic', 'UX Design'],
          aiPotential: 'Medium',
          aiAssistDescription: 'Can help structure feature specs and user stories',
          dependsOnTasks: ['ip-1', 'ip-2'],
          acceptanceCriteria: [
            'Feature list with priorities',
            'User stories for MVP features',
            'Acceptance criteria defined',
            'MVP scope agreed',
            'Stakeholder sign-off',
          ],
        }),
        createTask('ip-4', 'UX Design & Prototyping', 'Planning', 'UX/Product', {
          description: 'Design mobile-first portal interface. Create prototypes and test with installers. Ensure simplicity for field use.',
          stakeholders: ['Installers', 'Partner Ops'],
          estimatedHours: '16-24h',
          difficulty: 'Medium',
          toolsNeeded: ['Figma', 'Mobile prototyping'],
          knowledgeAreas: ['UX Design'],
          aiPotential: 'Medium',
          aiAssistDescription: 'Can suggest mobile UX patterns',
          dependsOnTasks: ['ip-3'],
          acceptanceCriteria: [
            'Mobile-first designs complete',
            'Prototype tested with 3+ installers',
            'Feedback incorporated',
            'Final designs approved',
            'Design system documented',
          ],
        }),
        createTask('ip-5', 'Authentication & Security Architecture', 'Planning', 'Tech Lead', {
          description: 'Design secure authentication for installers. Define role-based access, session management, and security measures.',
          stakeholders: ['Tech Team', 'Security', 'Legal'],
          estimatedHours: '12-16h',
          difficulty: 'Hard',
          toolsNeeded: ['Auth0', 'Security documentation'],
          knowledgeAreas: ['Security/Auth', 'Compliance/Legal'],
          aiPotential: 'Medium',
          aiAssistDescription: 'Can help with security architecture but needs expert review',
          dependsOnTasks: ['ip-2'],
          acceptanceCriteria: [
            'Auth flow documented',
            'Role-based access defined',
            'Session management specified',
            'Security requirements met',
            'Penetration testing plan',
          ],
          isFoundational: true,
          sharedWithProjects: ['installer-feedback-system', 'installer-quote-sync', 'installer-performance-tracking'],
        }),

        // DEVELOPMENT PHASE
        createTask('ip-6', 'Authentication System Implementation', 'Development', 'Developer', {
          description: 'Implement installer authentication with secure login, password reset, and session management.',
          stakeholders: ['Tech Team'],
          estimatedHours: '24-32h',
          difficulty: 'Hard',
          toolsNeeded: ['Auth0/Custom', 'JWT', 'Node.js'],
          knowledgeAreas: ['Security/Auth', 'API Integration'],
          aiPotential: 'Medium',
          aiAssistDescription: 'Can generate auth boilerplate but security needs review',
          dependsOnTasks: ['ip-5'],
          acceptanceCriteria: [
            'Login/logout working',
            'Password reset functional',
            'Session management implemented',
            'Security audit passed',
            'Multi-device support',
          ],
          isFoundational: true,
        }),
        createTask('ip-7', 'Lead Management Dashboard', 'Development', 'Developer', {
          description: 'Build lead management view: assigned leads, status updates, filtering, contact details, conversion tracking.',
          stakeholders: ['Installers', 'Partner Ops'],
          estimatedHours: '24-32h',
          difficulty: 'Medium',
          toolsNeeded: ['React', 'Backend APIs'],
          knowledgeAreas: ['Frontend/React', 'API Integration'],
          aiPotential: 'High',
          aiAssistDescription: 'Can generate dashboard components and data tables',
          dependsOnTasks: ['ip-6'],
          acceptanceCriteria: [
            'Lead list with filters',
            'Lead detail view',
            'Status update functionality',
            'Contact info accessible',
            'Conversion tracking visible',
            'Mobile optimized',
          ],
        }),
        createTask('ip-8', 'Performance Metrics View', 'Development', 'Developer', {
          description: 'Build performance dashboard: conversion rate, response time SLA, comparison to peers, trends.',
          stakeholders: ['Installers', 'Partner Ops'],
          estimatedHours: '16-24h',
          difficulty: 'Medium',
          toolsNeeded: ['React', 'Charts'],
          knowledgeAreas: ['Frontend/React', 'Data Analytics'],
          aiPotential: 'High',
          aiAssistDescription: 'Can generate chart components and metrics displays',
          dependsOnTasks: ['ip-7'],
          blockedBy: ['Stage timestamps in unified-data-layer'],
          acceptanceCriteria: [
            'Conversion rate displayed',
            'SLA compliance shown',
            'Trend charts working',
            'Peer comparison (anonymized)',
            'Goals and targets visible',
          ],
          sharedWithProjects: ['installer-performance-tracking'],
        }),
        createTask('ip-9', 'Feedback & Quote Submission', 'Development', 'Developer', {
          description: 'Build feedback forms and quote submission. Allow installers to report lead quality issues and submit offer amounts.',
          stakeholders: ['Installers', 'Partner Ops', 'Operations'],
          estimatedHours: '16-20h',
          difficulty: 'Easy',
          toolsNeeded: ['React', 'Backend APIs'],
          knowledgeAreas: ['Frontend/React', 'Business Logic'],
          aiPotential: 'High',
          aiAssistDescription: 'Can generate form components and validation',
          dependsOnTasks: ['ip-7'],
          acceptanceCriteria: [
            'Feedback form working',
            'Quote submission functional',
            'Validation in place',
            'Confirmation messages',
            'Data syncing to backend',
          ],
          sharedWithProjects: ['installer-feedback-system', 'installer-quote-sync'],
        }),
        createTask('ip-10', 'Notification System', 'Development', 'Developer', {
          description: 'Implement push notifications, email, and SMS for new leads and important updates.',
          stakeholders: ['Installers'],
          estimatedHours: '12-16h',
          difficulty: 'Medium',
          toolsNeeded: ['SendGrid', 'Twilio', 'Push notifications'],
          knowledgeAreas: ['API Integration', 'DevOps'],
          aiPotential: 'High',
          aiAssistDescription: 'Can generate notification templates and logic',
          dependsOnTasks: ['ip-6'],
          acceptanceCriteria: [
            'Email notifications working',
            'SMS notifications working',
            'Push notifications (if app)',
            'Preference management',
            'Delivery tracking',
          ],
        }),

        // TESTING PHASE
        createTask('ip-11', 'Installer Beta Program', 'Testing', 'Partner Ops', {
          description: 'Run beta with 3-5 installers for 3 weeks. Collect daily feedback. Fix issues. Validate usability in field conditions.',
          stakeholders: ['Installers', 'Tech Team'],
          estimatedHours: '24-36h',
          difficulty: 'Medium',
          toolsNeeded: ['Feedback tools', 'Support channel'],
          knowledgeAreas: ['Stakeholder Management', 'Process Design'],
          aiPotential: 'Low',
          aiAssistDescription: 'Human relationship management required',
          dependsOnTasks: ['ip-10'],
          acceptanceCriteria: [
            'Beta running 3+ weeks',
            'Daily feedback collected',
            'Critical bugs fixed',
            'Field usability validated',
            'Installer satisfaction >7/10',
          ],
          risks: ['Installer churn during beta', 'Field connectivity issues'],
        }),

        // TRAINING PHASE
        createTask('ip-12', 'Installer Onboarding Program', 'Training', 'Partner Ops', {
          description: 'Create onboarding materials: videos, guides, FAQ. Design self-service onboarding flow. Prepare support documentation.',
          stakeholders: ['Installers', 'Partner Ops'],
          estimatedHours: '16-24h',
          difficulty: 'Easy',
          toolsNeeded: ['Video recording', 'Documentation'],
          knowledgeAreas: ['Training & Documentation', 'Change Management'],
          aiPotential: 'High',
          aiAssistDescription: 'Can generate documentation and help scripts',
          dependsOnTasks: ['ip-11'],
          acceptanceCriteria: [
            'Onboarding videos created',
            'User guides published',
            'FAQ documented',
            'Self-service onboarding flow',
            'Support process defined',
          ],
        }),

        // ROLLOUT PHASE
        createTask('ip-13', 'Phased Installer Rollout', 'Rollout', 'Partner Ops', {
          description: 'Roll out to all installers in phases. Week 1: top performers. Week 2-3: remaining active. Provide hands-on support.',
          stakeholders: ['Installers', 'Partner Ops', 'Operations'],
          estimatedHours: '20-30h',
          difficulty: 'Medium',
          toolsNeeded: ['Communication', 'Support tools'],
          knowledgeAreas: ['Change Management', 'Stakeholder Management'],
          aiPotential: 'Low',
          aiAssistDescription: 'Human change management required',
          dependsOnTasks: ['ip-12'],
          acceptanceCriteria: [
            'All active installers onboarded',
            'Login success rate >95%',
            'Support tickets resolved <24h',
            'Old process deprecated',
            'Feedback positive >80%',
          ],
          successMetrics: [
            '100% installer adoption within 4 weeks',
            '50% reduction in lead response time',
            '30% increase in feedback submission',
          ],
        }),

        // MONITORING PHASE
        createTask('ip-14', 'Portal Performance & Iteration', 'Monitoring', 'Product', {
          description: 'Monitor portal usage, performance, and satisfaction. Establish feedback loop. Plan and deliver enhancements.',
          stakeholders: ['Installers', 'Partner Ops'],
          estimatedHours: 'Ongoing (6h/week)',
          difficulty: 'Easy',
          toolsNeeded: ['Analytics', 'Feedback tools'],
          knowledgeAreas: ['Data Analytics', 'Stakeholder Management'],
          aiPotential: 'Medium',
          aiAssistDescription: 'Can analyze usage patterns and suggest improvements',
          dependsOnTasks: ['ip-13'],
          acceptanceCriteria: [
            'Usage analytics dashboard live',
            'Monthly NPS survey running',
            'Enhancement backlog maintained',
            'Quarterly release cycle established',
          ],
        }),
      ],
    },

    // =========================================================================
    // 🧠 AI CORTEX
    // =========================================================================
    {
      projectId: 'ai-cortex',
      totalEstimatedHours: '200-280h',
      criticalPath: ['ac-1', 'ac-3', 'ac-5', 'ac-7', 'ac-9', 'ac-11', 'ac-13'],
      subTasks: [
        // DISCOVERY PHASE
        createTask('ac-1', 'AI Use Case Prioritization', 'Discovery', 'COO/Product', {
          description: 'Catalog all potential AI use cases across the business. Score by impact, feasibility, and data availability. Select top 5 for MVP.',
          stakeholders: ['CEO', 'All Department Heads'],
          estimatedHours: '16-24h',
          difficulty: 'Medium',
          toolsNeeded: ['Workshops', 'Prioritization matrix'],
          knowledgeAreas: ['Business Logic', 'LLM/Prompt Engineering', 'Stakeholder Management'],
          aiPotential: 'Medium',
          aiAssistDescription: 'Can help research AI capabilities and suggest use cases',
          acceptanceCriteria: [
            'Use case catalog complete (20+ ideas)',
            'Scoring matrix with impact/feasibility',
            'Top 5 MVP use cases selected',
            'Stakeholder alignment achieved',
            'Success metrics defined per use case',
          ],
          risks: ['Over-ambition', 'Data availability gaps'],
        }),
        createTask('ac-2', 'Data Readiness Assessment', 'Discovery', 'Tech Lead', {
          description: 'Assess data quality and availability for top AI use cases. Identify gaps, cleaning needs, and labeling requirements.',
          stakeholders: ['Tech Team', 'Operations'],
          estimatedHours: '12-16h',
          difficulty: 'Medium',
          toolsNeeded: ['Data analysis tools', 'Documentation'],
          knowledgeAreas: ['Data Analytics', 'Database/SQL'],
          aiPotential: 'Medium',
          aiAssistDescription: 'Can help analyze data patterns and quality',
          dependsOnTasks: ['ac-1'],
          acceptanceCriteria: [
            'Data availability mapped per use case',
            'Quality issues documented',
            'Cleaning requirements defined',
            'Labeling needs identified',
            'Data pipeline requirements specified',
          ],
        }),

        // PLANNING PHASE
        createTask('ac-3', 'AI Architecture Design', 'Planning', 'Tech Lead', {
          description: 'Design Cortex architecture: LLM integration layer, context aggregation, prompt management, agent framework, feedback loop.',
          stakeholders: ['Tech Team'],
          estimatedHours: '20-28h',
          difficulty: 'Hard',
          toolsNeeded: ['Architecture tools', 'Documentation'],
          knowledgeAreas: ['LLM/Prompt Engineering', 'API Integration', 'Database/SQL'],
          aiPotential: 'High',
          aiAssistDescription: 'Can help design architecture and suggest patterns',
          dependsOnTasks: ['ac-1', 'ac-2'],
          acceptanceCriteria: [
            'Architecture diagram complete',
            'LLM provider strategy defined',
            'Context aggregation approach',
            'Prompt versioning strategy',
            'Agent framework selection',
            'Feedback loop design',
            'Cost estimation',
          ],
          isFoundational: true,
          sharedWithProjects: ['sdr-portal', 'whatsapp-conversation-summary', 'campaign-os'],
        }),
        createTask('ac-4', 'LLM Provider Evaluation', 'Planning', 'Tech Lead', {
          description: 'Evaluate LLM providers (Claude, OpenAI, etc.) for cost, performance, and capabilities. Select primary and fallback providers.',
          stakeholders: ['Tech Team', 'Finance'],
          estimatedHours: '8-12h',
          difficulty: 'Medium',
          toolsNeeded: ['API access', 'Benchmarking'],
          knowledgeAreas: ['LLM/Prompt Engineering', 'Vendor Management'],
          aiPotential: 'High',
          aiAssistDescription: 'Can help benchmark and compare providers',
          dependsOnTasks: ['ac-1'],
          acceptanceCriteria: [
            'Provider comparison matrix',
            'Cost analysis per use case',
            'Performance benchmarks',
            'Primary provider selected',
            'Fallback strategy defined',
          ],
        }),

        // DEVELOPMENT PHASE
        createTask('ac-5', 'LLM Integration Layer', 'Development', 'Developer', {
          description: 'Build unified LLM integration layer with API abstraction, caching, rate limiting, error handling, and cost tracking.',
          stakeholders: ['Tech Team'],
          estimatedHours: '24-32h',
          difficulty: 'Hard',
          toolsNeeded: ['Node.js', 'API SDKs', 'Redis'],
          knowledgeAreas: ['API Integration', 'LLM/Prompt Engineering', 'DevOps'],
          aiPotential: 'High',
          aiAssistDescription: 'Can generate SDK wrappers and caching logic',
          dependsOnTasks: ['ac-3', 'ac-4'],
          acceptanceCriteria: [
            'API abstraction working',
            'Provider switching seamless',
            'Caching implemented',
            'Rate limiting in place',
            'Error handling robust',
            'Cost tracking enabled',
          ],
          isFoundational: true,
          sharedWithProjects: ['sdr-portal', 'whatsapp-conversation-summary', 'campaign-os', 'competitor-intel-agent'],
        }),
        createTask('ac-6', 'Context Aggregation Service', 'Development', 'Developer', {
          description: 'Build service to aggregate relevant context for AI queries: deal history, conversations, calls, lead attributes.',
          stakeholders: ['Tech Team'],
          estimatedHours: '24-32h',
          difficulty: 'Hard',
          toolsNeeded: ['Node.js', 'PostgreSQL', 'Redis'],
          knowledgeAreas: ['Database/SQL', 'Data Analytics', 'API Integration'],
          aiPotential: 'Medium',
          aiAssistDescription: 'Can help with query optimization and data aggregation',
          dependsOnTasks: ['ac-5'],
          blockedBy: ['Unified Data Layer complete'],
          acceptanceCriteria: [
            'Context aggregation working',
            'All relevant data sources included',
            'Performance <500ms for context fetch',
            'Caching for repeated queries',
            'Token budget management',
          ],
          isFoundational: true,
        }),
        createTask('ac-7', 'Prompt Template System', 'Development', 'Developer', {
          description: 'Build prompt management system with versioning, A/B testing, variables, and performance tracking.',
          stakeholders: ['Tech Team', 'Product'],
          estimatedHours: '16-20h',
          difficulty: 'Medium',
          toolsNeeded: ['Node.js', 'PostgreSQL'],
          knowledgeAreas: ['LLM/Prompt Engineering', 'Database/SQL'],
          aiPotential: 'High',
          aiAssistDescription: 'Can generate prompt templates and management logic',
          dependsOnTasks: ['ac-5'],
          acceptanceCriteria: [
            'Prompt versioning working',
            'Variables system functional',
            'A/B testing capability',
            'Performance tracking',
            'Rollback capability',
          ],
        }),
        createTask('ac-8', 'MVP Use Case Implementation', 'Development', 'Developer', {
          description: 'Implement top 5 MVP AI use cases: conversation summaries, prioritization, script assistance, pattern detection, recommendations.',
          stakeholders: ['SDR Team', 'Operations'],
          estimatedHours: '40-56h',
          difficulty: 'Hard',
          toolsNeeded: ['Full Cortex stack'],
          knowledgeAreas: ['LLM/Prompt Engineering', 'Business Logic'],
          aiPotential: 'High',
          aiAssistDescription: 'Core AI work - heavy AI assistance possible',
          dependsOnTasks: ['ac-5', 'ac-6', 'ac-7'],
          acceptanceCriteria: [
            'All 5 MVP use cases working',
            'Accuracy >70% per use case',
            'Response time <3s',
            'Edge cases handled',
            'Fallback behavior defined',
          ],
        }),

        // TESTING PHASE
        createTask('ac-9', 'AI Quality & Accuracy Testing', 'Testing', 'QA/Product', {
          description: 'Comprehensive testing of AI outputs. Create test datasets, measure accuracy, identify failure modes, tune prompts.',
          stakeholders: ['Tech Team', 'Operations'],
          estimatedHours: '24-36h',
          difficulty: 'Hard',
          toolsNeeded: ['Test datasets', 'Evaluation tools'],
          knowledgeAreas: ['Data Analytics', 'LLM/Prompt Engineering'],
          aiPotential: 'Medium',
          aiAssistDescription: 'Can help generate test cases and analyze results',
          dependsOnTasks: ['ac-8'],
          acceptanceCriteria: [
            'Test datasets created per use case',
            'Accuracy metrics established',
            'Failure modes documented',
            'Prompts tuned for accuracy',
            'Performance baseline established',
          ],
          risks: ['AI hallucinations', 'Edge case failures'],
        }),
        createTask('ac-10', 'User Acceptance Testing', 'Testing', 'Operations', {
          description: 'UAT with SDR team and stakeholders. Validate AI outputs are useful and accurate in real workflows.',
          stakeholders: ['SDR Team', 'Operations', 'Sales Lead'],
          estimatedHours: '16-24h',
          difficulty: 'Medium',
          toolsNeeded: ['UAT process', 'Feedback tools'],
          knowledgeAreas: ['Stakeholder Management', 'Process Design'],
          aiPotential: 'Low',
          aiAssistDescription: 'Human judgment required',
          dependsOnTasks: ['ac-9'],
          acceptanceCriteria: [
            'UAT with 5+ users completed',
            'Usefulness validated >7/10',
            'Critical feedback addressed',
            'Sign-off from stakeholders',
          ],
        }),

        // TRAINING PHASE
        createTask('ac-11', 'AI User Training & Guidelines', 'Training', 'Operations', {
          description: 'Train users on AI capabilities, limitations, and best practices. Create guidelines for when to trust vs. verify AI outputs.',
          stakeholders: ['All Teams'],
          estimatedHours: '12-16h',
          difficulty: 'Easy',
          toolsNeeded: ['Training materials', 'Documentation'],
          knowledgeAreas: ['Training & Documentation', 'Change Management'],
          aiPotential: 'High',
          aiAssistDescription: 'Can generate training materials and guidelines',
          dependsOnTasks: ['ac-10'],
          acceptanceCriteria: [
            'Training materials created',
            'AI usage guidelines published',
            'Training sessions completed',
            'FAQ documented',
            'Escalation process for AI errors',
          ],
        }),

        // ROLLOUT PHASE
        createTask('ac-12', 'Gradual Cortex Rollout', 'Rollout', 'Product', {
          description: 'Roll out Cortex features gradually. Start with low-risk use cases, expand based on performance and feedback.',
          stakeholders: ['All Teams', 'COO'],
          estimatedHours: '16-24h',
          difficulty: 'Medium',
          toolsNeeded: ['Feature flags', 'Analytics'],
          knowledgeAreas: ['Change Management', 'DevOps'],
          aiPotential: 'Low',
          aiAssistDescription: 'Human judgment on rollout pace required',
          dependsOnTasks: ['ac-11'],
          acceptanceCriteria: [
            'Phased rollout plan executed',
            'Feature flags working',
            'Rollback plan tested',
            'Adoption tracking active',
            'Feedback loop established',
          ],
          successMetrics: [
            'All MVP features live within 4 weeks',
            'Zero critical AI failures',
            'User satisfaction >8/10',
          ],
        }),

        // MONITORING PHASE
        createTask('ac-13', 'Continuous AI Improvement', 'Monitoring', 'Product/Tech Lead', {
          description: 'Establish continuous improvement: monitor accuracy, collect feedback, tune prompts, add use cases.',
          stakeholders: ['All Teams'],
          estimatedHours: 'Ongoing (8h/week)',
          difficulty: 'Medium',
          toolsNeeded: ['Analytics', 'Feedback tools', 'Prompt tuning'],
          knowledgeAreas: ['LLM/Prompt Engineering', 'Data Analytics'],
          aiPotential: 'High',
          aiAssistDescription: 'Can help analyze patterns and suggest prompt improvements',
          dependsOnTasks: ['ac-12'],
          acceptanceCriteria: [
            'Accuracy monitoring dashboard',
            'Weekly prompt review process',
            'User feedback integration',
            'New use case pipeline',
            'Cost optimization ongoing',
          ],
        }),
      ],
    },

    // =========================================================================
    // 📈 CAMPAIGN OS
    // =========================================================================
    {
      projectId: 'campaign-os',
      totalEstimatedHours: '160-220h',
      criticalPath: ['cos-1', 'cos-3', 'cos-5', 'cos-8', 'cos-10', 'cos-12'],
      subTasks: [
        createTask('cos-1', 'Marketing Workflow Analysis', 'Discovery', 'Marketing Lead', {
          description: 'Document current paid media workflow: platforms used, reporting process, optimization methods, pain points.',
          stakeholders: ['Marketing', 'Finance', 'COO'],
          estimatedHours: '8-12h',
          difficulty: 'Easy',
          toolsNeeded: ['Interviews', 'Documentation'],
          knowledgeAreas: ['Process Design', 'Business Logic'],
          aiPotential: 'Low',
          aiAssistDescription: 'Human domain expertise required',
          acceptanceCriteria: [
            'Current workflow documented',
            'Tools inventory complete',
            'Pain points prioritized',
            'Opportunity areas identified',
          ],
        }),
        createTask('cos-2', 'Platform API Access & Permissions', 'Discovery', 'Operations', {
          description: 'Secure API access for Meta, Google, TikTok. Document rate limits, data available, and permissions needed.',
          stakeholders: ['Marketing', 'Tech Team'],
          estimatedHours: '8-12h',
          difficulty: 'Medium',
          toolsNeeded: ['Platform developer consoles'],
          knowledgeAreas: ['Vendor Management', 'External APIs'],
          aiPotential: 'Low',
          aiAssistDescription: 'Platform-specific setup required',
          blockedBy: ['Ad account access', 'Developer verification'],
          acceptanceCriteria: [
            'Meta Ads API access confirmed',
            'Google Ads API access confirmed',
            'TikTok API access confirmed (if used)',
            'Rate limits documented',
            'Data availability mapped',
          ],
        }),
        createTask('cos-3', 'Attribution Model Definition', 'Planning', 'Marketing/Product', {
          description: 'Define attribution model: first-touch, last-touch, multi-touch. Map UTM parameters to CRM. Specify data requirements.',
          stakeholders: ['Marketing', 'Finance', 'Tech Lead'],
          estimatedHours: '12-16h',
          difficulty: 'Hard',
          toolsNeeded: ['Analytics', 'Documentation'],
          knowledgeAreas: ['Data Analytics', 'Business Logic'],
          aiPotential: 'Medium',
          aiAssistDescription: 'Can help research attribution models and best practices',
          dependsOnTasks: ['cos-1'],
          acceptanceCriteria: [
            'Attribution model selected',
            'UTM parameter standard defined',
            'CRM mapping documented',
            'Data pipeline requirements',
            'Stakeholder agreement',
          ],
          isFoundational: true,
          sharedWithProjects: ['reporting-hub'],
        }),
        createTask('cos-4', 'Technical Architecture', 'Planning', 'Tech Lead', {
          description: 'Design Campaign OS architecture: API integrations, data warehouse, dashboard, AI components.',
          stakeholders: ['Tech Team'],
          estimatedHours: '12-16h',
          difficulty: 'Hard',
          toolsNeeded: ['Architecture tools'],
          knowledgeAreas: ['API Integration', 'Database/SQL', 'External APIs'],
          aiPotential: 'High',
          aiAssistDescription: 'Can help design architecture and integration patterns',
          dependsOnTasks: ['cos-2', 'cos-3'],
          acceptanceCriteria: [
            'Architecture diagram complete',
            'Integration approach defined',
            'Data model designed',
            'Performance requirements',
          ],
        }),
        createTask('cos-5', 'Ad Platform Integrations', 'Development', 'Developer', {
          description: 'Build integrations with Meta and Google Ads APIs. Pull campaign data, spend, and performance metrics.',
          stakeholders: ['Marketing', 'Tech Team'],
          estimatedHours: '32-44h',
          difficulty: 'Hard',
          toolsNeeded: ['Meta Ads API', 'Google Ads API', 'Node.js'],
          knowledgeAreas: ['API Integration', 'External APIs'],
          aiPotential: 'Medium',
          aiAssistDescription: 'Can help with API integration patterns but platform-specific',
          dependsOnTasks: ['cos-2', 'cos-4'],
          acceptanceCriteria: [
            'Meta data syncing daily',
            'Google data syncing daily',
            'Campaign metrics accurate',
            'Spend data reconciled',
            'Error handling robust',
          ],
        }),
        createTask('cos-6', 'Attribution Pipeline', 'Development', 'Developer', {
          description: 'Build attribution pipeline: UTM capture, CRM linking, conversion tracking, multi-touch attribution calculations.',
          stakeholders: ['Marketing', 'Sales'],
          estimatedHours: '20-28h',
          difficulty: 'Hard',
          toolsNeeded: ['Node.js', 'PostgreSQL'],
          knowledgeAreas: ['Data Analytics', 'Database/SQL', 'Business Logic'],
          aiPotential: 'Medium',
          aiAssistDescription: 'Can help with attribution logic but business rules complex',
          dependsOnTasks: ['cos-3', 'cos-5'],
          acceptanceCriteria: [
            'UTM capture working',
            'CRM linking accurate',
            'Conversion tracking functional',
            'Attribution calculated correctly',
            'Validated against manual calcs',
          ],
          sharedWithProjects: ['reporting-hub'],
        }),
        createTask('cos-7', 'Campaign Dashboard', 'Development', 'Developer', {
          description: 'Build dashboard: spend by channel, ROI by campaign, conversion funnel, creative performance.',
          stakeholders: ['Marketing', 'Leadership'],
          estimatedHours: '24-32h',
          difficulty: 'Medium',
          toolsNeeded: ['React', 'Charts'],
          knowledgeAreas: ['Frontend/React', 'Data Analytics'],
          aiPotential: 'High',
          aiAssistDescription: 'Can generate dashboard components and visualizations',
          dependsOnTasks: ['cos-5', 'cos-6'],
          acceptanceCriteria: [
            'Spend breakdown by channel',
            'ROI calculations correct',
            'Funnel visualization',
            'Creative performance view',
            'Date range filters',
          ],
        }),
        createTask('cos-8', 'AI Creative Analysis', 'Development', 'Developer', {
          description: 'Build AI feature to analyze winning ads and suggest variations. Identify patterns in high-performing creatives.',
          stakeholders: ['Marketing'],
          estimatedHours: '16-24h',
          difficulty: 'Medium',
          toolsNeeded: ['LLM APIs', 'Node.js'],
          knowledgeAreas: ['LLM/Prompt Engineering'],
          aiPotential: 'High',
          aiAssistDescription: 'Core AI feature - can generate analysis prompts',
          dependsOnTasks: ['cos-7'],
          acceptanceCriteria: [
            'Creative analysis working',
            'Patterns identified accurately',
            'Suggestions actionable',
            'Performance correlation shown',
          ],
          sharedWithProjects: ['competitor-intel-agent'],
        }),
        createTask('cos-9', 'Data Validation & UAT', 'Testing', 'Marketing/QA', {
          description: 'Validate all data against ad platform dashboards. User testing with marketing team.',
          stakeholders: ['Marketing', 'Finance'],
          estimatedHours: '16-24h',
          difficulty: 'Medium',
          toolsNeeded: ['Spreadsheets', 'Platform dashboards'],
          knowledgeAreas: ['Data Analytics'],
          aiPotential: 'Low',
          aiAssistDescription: 'Human validation required',
          dependsOnTasks: ['cos-7', 'cos-8'],
          acceptanceCriteria: [
            'Data matches platform dashboards',
            'ROI calculations validated by Finance',
            'UAT completed with Marketing',
            'Discrepancies documented and explained',
          ],
        }),
        createTask('cos-10', 'Marketing Team Training', 'Training', 'Marketing Lead', {
          description: 'Train marketing team on Campaign OS. Document workflows and best practices.',
          stakeholders: ['Marketing'],
          estimatedHours: '8-12h',
          difficulty: 'Easy',
          toolsNeeded: ['Training materials'],
          knowledgeAreas: ['Training & Documentation'],
          aiPotential: 'High',
          aiAssistDescription: 'Can generate training materials',
          dependsOnTasks: ['cos-9'],
          acceptanceCriteria: [
            'Training completed',
            'Documentation published',
            'Best practices defined',
          ],
        }),
        createTask('cos-11', 'Production Launch', 'Rollout', 'Marketing Lead', {
          description: 'Launch Campaign OS. Migrate from old reporting process. Monitor accuracy and adoption.',
          stakeholders: ['Marketing', 'Leadership'],
          estimatedHours: '8-12h',
          difficulty: 'Easy',
          toolsNeeded: ['Deployment'],
          knowledgeAreas: ['Change Management'],
          aiPotential: 'Low',
          aiAssistDescription: 'Human change management',
          dependsOnTasks: ['cos-10'],
          acceptanceCriteria: [
            'System live',
            'Team using daily',
            'Old process deprecated',
          ],
          successMetrics: [
            '100% of reporting through Campaign OS',
            '75% reduction in reporting time',
            'ROI visibility within 24h of spend',
          ],
        }),
        createTask('cos-12', 'Ongoing Optimization', 'Monitoring', 'Marketing Lead', {
          description: 'Continuous improvement: data quality monitoring, new features, AI enhancement.',
          stakeholders: ['Marketing', 'Tech Team'],
          estimatedHours: 'Ongoing (4h/week)',
          difficulty: 'Easy',
          toolsNeeded: ['Analytics'],
          knowledgeAreas: ['Data Analytics'],
          aiPotential: 'Medium',
          aiAssistDescription: 'Can help analyze patterns',
          dependsOnTasks: ['cos-11'],
          acceptanceCriteria: [
            'Weekly data quality review',
            'Feature backlog maintained',
            'AI suggestions improving',
          ],
        }),
      ],
    },

    // Add more projects following the same comprehensive pattern...
    // For brevity, I'll add skeleton entries for remaining projects
    // Each should follow the same Discovery → Planning → Development → Testing → Training → Rollout → Monitoring pattern

    // =========================================================================
    // ADDITIONAL PROJECTS (Skeleton - expand as needed)
    // =========================================================================
    {
      projectId: 'data-quality-monitor',
      totalEstimatedHours: '80-100h',
      criticalPath: ['dqm-1', 'dqm-3', 'dqm-5', 'dqm-7', 'dqm-9'],
      subTasks: [
        createTask('dqm-1', 'Data Quality Requirements Gathering', 'Discovery', 'Operations', {
          description: 'Define data quality rules with all stakeholders. Document thresholds for freshness, completeness, accuracy.',
          stakeholders: ['All Teams'],
          estimatedHours: '8-12h',
          difficulty: 'Medium',
          toolsNeeded: ['Workshops', 'Documentation'],
          knowledgeAreas: ['Data Analytics', 'Business Logic'],
          aiPotential: 'Medium',
          aiAssistDescription: 'Can suggest data quality metrics',
          acceptanceCriteria: ['Quality rules documented', 'Thresholds agreed'],
        }),
        createTask('dqm-2', 'Alert Channel Setup', 'Planning', 'Operations', {
          description: 'Set up Slack channels and email lists for data quality alerts. Define escalation paths.',
          stakeholders: ['Tech Team', 'Operations'],
          estimatedHours: '4-6h',
          difficulty: 'Easy',
          toolsNeeded: ['Slack', 'Email'],
          knowledgeAreas: ['DevOps'],
          aiPotential: 'High',
          aiAssistDescription: 'Can generate channel structure',
          dependsOnTasks: ['dqm-1'],
          acceptanceCriteria: ['Channels created', 'Escalation defined'],
        }),
        createTask('dqm-3', 'Quality Scoring Engine', 'Development', 'Developer', {
          description: 'Build engine to calculate quality scores for each data source. Store historical scores.',
          stakeholders: ['Tech Team'],
          estimatedHours: '16-24h',
          difficulty: 'Medium',
          toolsNeeded: ['Node.js', 'PostgreSQL'],
          knowledgeAreas: ['Database/SQL', 'Data Analytics'],
          aiPotential: 'High',
          aiAssistDescription: 'Can generate scoring algorithms',
          dependsOnTasks: ['dqm-1'],
          acceptanceCriteria: ['Scoring working', 'Historical tracking', 'API endpoint'],
        }),
        createTask('dqm-4', 'Alerting System', 'Development', 'Developer', {
          description: 'Implement alerts for quality degradation. Send to Slack and email based on severity.',
          stakeholders: ['Operations'],
          estimatedHours: '12-16h',
          difficulty: 'Easy',
          toolsNeeded: ['Slack API', 'SendGrid'],
          knowledgeAreas: ['API Integration'],
          aiPotential: 'High',
          aiAssistDescription: 'Can generate alert logic',
          dependsOnTasks: ['dqm-2', 'dqm-3'],
          acceptanceCriteria: ['Alerts firing correctly', 'Severity levels working'],
          isFoundational: true,
          sharedWithProjects: ['answer-rate-monitoring', 'installer-performance-tracking'],
        }),
        createTask('dqm-5', 'Monitoring Dashboard', 'Development', 'Developer', {
          description: 'Build dashboard showing quality scores, trends, and active alerts.',
          stakeholders: ['Operations', 'Tech Lead'],
          estimatedHours: '12-16h',
          difficulty: 'Medium',
          toolsNeeded: ['React', 'Charts'],
          knowledgeAreas: ['Frontend/React', 'Data Analytics'],
          aiPotential: 'High',
          aiAssistDescription: 'Can generate dashboard components',
          dependsOnTasks: ['dqm-3'],
          acceptanceCriteria: ['Dashboard live', 'Quality scores visible', 'Trends shown'],
        }),
        createTask('dqm-6', 'Auto-Remediation Scripts', 'Development', 'Developer', {
          description: 'Build auto-remediation for common issues: re-sync stale data, fill missing fields from sources.',
          stakeholders: ['Tech Team'],
          estimatedHours: '8-12h',
          difficulty: 'Medium',
          toolsNeeded: ['Node.js'],
          knowledgeAreas: ['DevOps', 'Database/SQL'],
          aiPotential: 'Medium',
          aiAssistDescription: 'Can help with remediation patterns',
          dependsOnTasks: ['dqm-3'],
          acceptanceCriteria: ['Auto-fix working for top 3 issues'],
        }),
        createTask('dqm-7', 'Testing & Validation', 'Testing', 'QA', {
          description: 'Test quality scoring accuracy. Validate alerts fire correctly. Test auto-remediation.',
          stakeholders: ['Operations'],
          estimatedHours: '8-12h',
          difficulty: 'Easy',
          toolsNeeded: ['Test scenarios'],
          knowledgeAreas: ['Data Analytics'],
          aiPotential: 'Medium',
          aiAssistDescription: 'Can generate test cases',
          dependsOnTasks: ['dqm-5', 'dqm-6'],
          acceptanceCriteria: ['Scoring validated', 'Alerts tested', 'Remediation working'],
        }),
        createTask('dqm-8', 'Ops Team Training', 'Training', 'Operations', {
          description: 'Train ops team on responding to data quality alerts. Document runbooks.',
          stakeholders: ['Operations'],
          estimatedHours: '6-8h',
          difficulty: 'Easy',
          toolsNeeded: ['Documentation'],
          knowledgeAreas: ['Training & Documentation'],
          aiPotential: 'High',
          aiAssistDescription: 'Can generate runbooks',
          dependsOnTasks: ['dqm-7'],
          acceptanceCriteria: ['Training complete', 'Runbooks published'],
        }),
        createTask('dqm-9', 'Production Deployment', 'Rollout', 'Tech Lead', {
          description: 'Deploy to production. Enable monitoring for all data sources.',
          stakeholders: ['Tech Team', 'Operations'],
          estimatedHours: '4-6h',
          difficulty: 'Easy',
          toolsNeeded: ['Deployment'],
          knowledgeAreas: ['DevOps'],
          aiPotential: 'Medium',
          aiAssistDescription: 'Can help with deployment config',
          dependsOnTasks: ['dqm-8'],
          acceptanceCriteria: ['Monitoring active', 'All sources covered'],
          successMetrics: ['Data quality score >95%', 'Alert response <1h'],
        }),
      ],
    },

    {
      projectId: 'funnel-automation-os',
      totalEstimatedHours: '200-260h',
      criticalPath: ['fao-1', 'fao-3', 'fao-5', 'fao-8', 'fao-10', 'fao-12'],
      subTasks: [
        createTask('fao-1', 'Current Funnel Analysis', 'Discovery', 'Operations', {
          description: 'Map current lead funnel: touchpoints, conversion rates, drop-off points, manual interventions.',
          stakeholders: ['SDR Team', 'Operations', 'Marketing'],
          estimatedHours: '12-16h',
          difficulty: 'Medium',
          toolsNeeded: ['Analytics', 'Interviews'],
          knowledgeAreas: ['Process Design', 'Data Analytics'],
          aiPotential: 'Medium',
          aiAssistDescription: 'Can help analyze funnel data',
          acceptanceCriteria: ['Funnel map complete', 'Drop-offs quantified', 'Automation opportunities identified'],
        }),
        createTask('fao-2', 'WhatsApp Bot Strategy', 'Planning', 'Product', {
          description: 'Define bot conversation flows for qualification, scheduling, and FAQs. Design handoff to human.',
          stakeholders: ['SDR Team', 'Operations'],
          estimatedHours: '16-20h',
          difficulty: 'Medium',
          toolsNeeded: ['Flow design tools'],
          knowledgeAreas: ['Business Logic', 'UX Design'],
          aiPotential: 'High',
          aiAssistDescription: 'Can help design conversation flows',
          dependsOnTasks: ['fao-1'],
          acceptanceCriteria: ['Flows documented', 'Handoff rules defined', 'SDR approval'],
        }),
        createTask('fao-3', 'WhatsApp API Integration', 'Development', 'Developer', {
          description: 'Integrate with WhatsApp Business API via Woztell for programmatic messaging.',
          stakeholders: ['Tech Team'],
          estimatedHours: '24-32h',
          difficulty: 'Hard',
          toolsNeeded: ['Woztell API', 'Node.js'],
          knowledgeAreas: ['API Integration', 'External APIs'],
          aiPotential: 'Medium',
          aiAssistDescription: 'Can help with integration patterns',
          dependsOnTasks: ['fao-2'],
          blockedBy: ['WhatsApp Business verification'],
          acceptanceCriteria: ['Send messages working', 'Receive webhooks working', 'Error handling robust'],
          isFoundational: true,
          sharedWithProjects: ['whatsapp-conversation-summary'],
        }),
        createTask('fao-4', 'Flow Builder UI', 'Development', 'Developer', {
          description: 'Build visual flow builder for creating and editing conversation flows.',
          stakeholders: ['Operations', 'Product'],
          estimatedHours: '32-44h',
          difficulty: 'Hard',
          toolsNeeded: ['React', 'React Flow'],
          knowledgeAreas: ['Frontend/React', 'UX Design'],
          aiPotential: 'Medium',
          aiAssistDescription: 'Can help with component architecture',
          dependsOnTasks: ['fao-3'],
          acceptanceCriteria: ['Drag-drop flow building', 'Conditions and branches', 'Preview functionality'],
        }),
        createTask('fao-5', 'Routing Engine', 'Development', 'Developer', {
          description: 'Build lead routing engine: rules-based assignment, availability check, performance-based distribution.',
          stakeholders: ['Operations', 'SDR Team'],
          estimatedHours: '20-28h',
          difficulty: 'Medium',
          toolsNeeded: ['Node.js', 'Redis'],
          knowledgeAreas: ['Business Logic', 'Database/SQL'],
          aiPotential: 'Medium',
          aiAssistDescription: 'Can help with routing logic',
          dependsOnTasks: ['fao-3'],
          acceptanceCriteria: ['Rule-based routing working', 'Availability considered', 'Performance weighting'],
          isFoundational: true,
          sharedWithProjects: ['dynamic-allocation-engine'],
        }),
        createTask('fao-6', 'A/B Testing Framework', 'Development', 'Developer', {
          description: 'Build A/B testing for flows: split traffic, track conversions, statistical significance.',
          stakeholders: ['Product', 'Marketing'],
          estimatedHours: '16-20h',
          difficulty: 'Medium',
          toolsNeeded: ['Node.js', 'PostgreSQL'],
          knowledgeAreas: ['Data Analytics', 'Business Logic'],
          aiPotential: 'High',
          aiAssistDescription: 'Can generate A/B testing logic',
          dependsOnTasks: ['fao-4'],
          acceptanceCriteria: ['Traffic splitting working', 'Conversion tracking', 'Significance calculations'],
          sharedWithProjects: ['campaign-os'],
        }),
        createTask('fao-7', 'Analytics Dashboard', 'Development', 'Developer', {
          description: 'Build funnel analytics: flow performance, conversion rates, drop-off analysis.',
          stakeholders: ['Operations', 'Leadership'],
          estimatedHours: '16-20h',
          difficulty: 'Medium',
          toolsNeeded: ['React', 'Charts'],
          knowledgeAreas: ['Frontend/React', 'Data Analytics'],
          aiPotential: 'High',
          aiAssistDescription: 'Can generate dashboard components',
          dependsOnTasks: ['fao-5', 'fao-6'],
          acceptanceCriteria: ['Funnel metrics visible', 'Flow comparison', 'Drop-off identification'],
        }),
        createTask('fao-8', 'Integration Testing', 'Testing', 'QA', {
          description: 'End-to-end testing of flows. Test all branches, error cases, and edge scenarios.',
          stakeholders: ['Tech Team', 'Operations'],
          estimatedHours: '16-24h',
          difficulty: 'Medium',
          toolsNeeded: ['Test scenarios', 'WhatsApp sandbox'],
          knowledgeAreas: ['API Integration'],
          aiPotential: 'Medium',
          aiAssistDescription: 'Can help generate test cases',
          dependsOnTasks: ['fao-7'],
          acceptanceCriteria: ['All flows tested', 'Error handling verified', 'Edge cases covered'],
        }),
        createTask('fao-9', 'Ops Training & Documentation', 'Training', 'Operations', {
          description: 'Train ops team on flow builder and monitoring. Document best practices.',
          stakeholders: ['Operations'],
          estimatedHours: '12-16h',
          difficulty: 'Easy',
          toolsNeeded: ['Training materials'],
          knowledgeAreas: ['Training & Documentation'],
          aiPotential: 'High',
          aiAssistDescription: 'Can generate training materials',
          dependsOnTasks: ['fao-8'],
          acceptanceCriteria: ['Training complete', 'Documentation published'],
        }),
        createTask('fao-10', 'Pilot Launch', 'Rollout', 'Operations', {
          description: 'Launch pilot with subset of leads. Monitor performance and iterate.',
          stakeholders: ['Operations', 'SDR Team'],
          estimatedHours: '16-24h',
          difficulty: 'Medium',
          toolsNeeded: ['Monitoring'],
          knowledgeAreas: ['Change Management'],
          aiPotential: 'Low',
          aiAssistDescription: 'Human judgment for pilot',
          dependsOnTasks: ['fao-9'],
          acceptanceCriteria: ['Pilot running', 'Metrics tracking', 'Issues resolved'],
        }),
        createTask('fao-11', 'Full Rollout', 'Rollout', 'Operations', {
          description: 'Expand to all eligible leads. Deprecate manual processes where automated.',
          stakeholders: ['All Teams'],
          estimatedHours: '8-12h',
          difficulty: 'Easy',
          toolsNeeded: ['Communication'],
          knowledgeAreas: ['Change Management'],
          aiPotential: 'Low',
          aiAssistDescription: 'Human change management',
          dependsOnTasks: ['fao-10'],
          acceptanceCriteria: ['All leads processed through system', 'Manual processes deprecated'],
          successMetrics: ['50% increase in contact rate', '30% reduction in SDR time on initial contact', '25% improvement in qualification rate'],
        }),
        createTask('fao-12', 'Continuous Optimization', 'Monitoring', 'Product', {
          description: 'Ongoing flow optimization based on data. A/B test improvements. Add new flows.',
          stakeholders: ['Operations', 'Product'],
          estimatedHours: 'Ongoing (8h/week)',
          difficulty: 'Medium',
          toolsNeeded: ['Analytics'],
          knowledgeAreas: ['Data Analytics', 'Business Logic'],
          aiPotential: 'High',
          aiAssistDescription: 'Can analyze flow performance and suggest improvements',
          dependsOnTasks: ['fao-11'],
          acceptanceCriteria: ['Weekly optimization reviews', 'Continuous A/B testing', 'Flow performance improving'],
        }),
      ],
    },
  ];
}
